### ISSUE TITLE
Why are we closing the connection as soon as we have created it every time?

### ISSUE THREAD

**Issue by mitcje** [ikasanEIP/ikasan#349]
https://github.com/ikasanEIP/ikasan/blob/f80ad68154ec643e699c33cf86a08a33dd5043a4/ikasaneip/component/endpoint/jms-spring/src/main/java/org/springframework/jms/listener/IkasanMessageListenerContainer.java#L143

**Comment by andrzej-majewski** [comment]
If I remember correctly, this connection is only used to lookup the destination. I remember having same question to @ken. 
Bare in mind that we pass the connectionFactory to underlaying spring DLC, not the connection.

**Comment by drawson** [comment]
@andrzej-majewski  is correct, I think we only have the Ikasan MLC to allow setting of the destination at start of the flow. Otherwise we would never be able to change the destination in dashboard/blue console.

**Comment by mitcje** [comment]
Creates a lot of noise in the logs with AMQ shutting down sessions.

**Comment by mitcje** [comment]
ok, it looks much worse when using AMQ embedded for samples and test cases. Will close the jira as Wont Fix

**Comment by chanchaihong** [comment]
Sorry for the late reply and @andrzej-majewski and @drawson are right. It is used to create JMS destination in runtime instead of using JNDI lookup.

Later we found out that we can specify multiple server URLs in destinationJndiProperties (java.naming.provider.url) for messaging server failover. So it is fine to ignore this PR. Thanks very much.
